Repository jenkinsci/extra-tool-installers-plugin, pull requests merged in 2025-02, with the labels that each got.

#141 Bump bom to 4228.v0a_71308d905b_
  pom.xml
Labels: dependencies

#142 feat(java): Require Jenkins core 2.479.3 and Java 17.
  pom.xml
Labels: enhancement, dependencies

#143 Migrate to httpclient5
  pom.xml
  src/main/java/io/jenkins/plugins/extratoolinstallers/installers/AuthenticatedDownloadCallable.java
  src/main/java/io/jenkins/plugins/extratoolinstallers/installers/AuthenticatedZipExtractionInstaller.java
Labels: developer

#146 Fix basic authentication
  pom.xml
  src/main/java/io/jenkins/plugins/extratoolinstallers/installers/AuthenticatedDownloadCallable.java
  src/test/java/io/jenkins/plugins/extratoolinstallers/installers/AuthenticatedZipExtractionInstallerTest.java
  src/test/resources/__files/dummy.zip
Labels: bug

#147 Migrate tests to JUnit5
  src/test/java/io/jenkins/plugins/extratoolinstallers/installers/AnyOfInstallerTest.java
  src/test/java/io/jenkins/plugins/extratoolinstallers/installers/IsAlreadyOnPathTest.java
  src/test/java/io/jenkins/plugins/extratoolinstallers/jcasc/ConfigurationAsCodeTest.java
Labels: tests
